<?php

$plugin = $plugin ?? $oPlugin ?? \JTL\Plugin\Helper::getPluginById('jtl_search');
define('JTLSEARCH_MANAGER_SERVER_URL', 'https://manager-jtlsearch.jtl-software.de/jtlsearch/manager/index.php');

// Pfade
define('JTLSEARCH_PFAD', $plugin->getPaths()->getBasePath());
define('JTLSEARCH_ADMIN_URL', $plugin->getPaths()->getAdminURL());

define('JTLSEARCH_PFAD_INCLUDES', JTLSEARCH_PFAD . 'includes/');
define('JTLSEARCH_PFAD_CLASSES', JTLSEARCH_PFAD . 'classes/');
define('JTLSEARCH_PFAD_ADMINMENU', JTLSEARCH_PFAD . PFAD_PLUGIN_ADMINMENU);

define('JTLSEARCH_ADMIN_CSS_URL_PATH', JTLSEARCH_ADMIN_URL . 'css/');
define('JTLSEARCH_ADMIN_TPL_PATH', JTLSEARCH_PFAD_ADMINMENU . 'template/');

define('JTLSEARCH_PFAD_FRONTEND', JTLSEARCH_PFAD . PFAD_PLUGIN_FRONTEND); 
define('JTLSEARCH_PFAD_LIBS', JTLSEARCH_PFAD . 'libs/');

define(
    'JTLSEARCH_URL_ADMINMENU_TESTPERIOD_TEMPLATES_CSS',
    $plugin->getPaths()->getAdminPath() . 'testperiod/templates/css/'
);
define(
    'JTLSEARCH_URL_ADMINMENU_TESTPERIOD_TEMPLATES_CSS_BASE',
    JTLSEARCH_URL_ADMINMENU_TESTPERIOD_TEMPLATES_CSS . 'base.css'
);

define('JTLSEARCH_PFAD_ADMINMENU_VERWALTUNG', JTLSEARCH_PFAD_ADMINMENU . 'verwaltung/');
define('JTLSEARCH_PFAD_ADMINMENU_VERWALTUNG_INCLUDES', JTLSEARCH_PFAD_ADMINMENU_VERWALTUNG . 'includes/');
define('JTLSEARCH_PFAD_ADMINMENU_VERWALTUNG_TEMPLATES', JTLSEARCH_PFAD_ADMINMENU_VERWALTUNG . 'templates/');
define('JTLSEARCH_PFAD_ADMINMENU_VERWALTUNG_CLASSES', JTLSEARCH_PFAD_ADMINMENU_VERWALTUNG . 'classes/');

define('JTLSEARCH_PFAD_ADMINMENU_SETTINGS', JTLSEARCH_PFAD_ADMINMENU . 'settings/');
define('JTLSEARCH_PFAD_ADMINMENU_SETTINGS_INCLUDES', JTLSEARCH_PFAD_ADMINMENU_SETTINGS . 'includes/');
define('JTLSEARCH_PFAD_ADMINMENU_SETTINGS_TEMPLATES', JTLSEARCH_PFAD_ADMINMENU_SETTINGS . 'templates/');
define('JTLSEARCH_PFAD_ADMINMENU_SETTINGS_CLASSES', JTLSEARCH_PFAD_ADMINMENU_SETTINGS . 'classes/');

// CURL Server Pass
define('JTLSEARCH_SECRET_KEY', '5Ce5CSwQfq7JpAhB');

// Stat types
define('JTLSEARCH_STAT_TYPE_VIEWED', 1);
define('JTLSEARCH_STAT_TYPE_BASKET', 2);
define('JTLSEARCH_STAT_TYPE_RECOMMEND', 3);
define('JTLSEARCH_STAT_TYPE_WISHLIST', 4);
define('JTLSEARCH_STAT_TYPE_DEMAND', 5);
define('JTLSEARCH_STAT_TYPE_NOTIFY', 6);
define('JTLSEARCH_STAT_TYPE_COMPARE', 7);

// Export-Limit pro Run
define('JTLSEARCH_LIMIT_N_METHOD_1', JOBQUEUE_LIMIT_M_EXPORTE);
define('JTLSEARCH_LIMIT_N_METHOD_2', 100);
define('JTLSEARCH_LIMIT_N_METHOD_3', 500);

// Deltaexport
define('JTLSEARCH_DELTAEXPORT_ITEMS_MAX', 500);
define('JTLSEARCH_DELTAEXPORT_TRIGGER_CRON', true);

define('JTLSEARCH_URL_EXPORTFILE_DIR', Shop::getURL() . '/' . PFAD_EXPORT);
define('JTLSEARCH_PFAD_EXPORTFILE_DIR', PFAD_ROOT . PFAD_EXPORT);

define('JTLSEARCH_URL_EXPORTFILE_ZIP', JTLSEARCH_URL_EXPORTFILE_DIR . 'jtlsearch.zip');
define('JTLSEARCH_PFAD_EXPORTFILE_ZIP', JTLSEARCH_PFAD_EXPORTFILE_DIR . 'jtlsearch.zip');

define('JTLSEARCH_URL_DELTA_EXPORTFILE_ZIP', JTLSEARCH_URL_EXPORTFILE_DIR . 'delta_jtlsearch' . time() . '.zip');
define('JTLSEARCH_PFAD_DELTA_EXPORTFILE_ZIP', JTLSEARCH_PFAD_EXPORTFILE_DIR . 'delta_jtlsearch' . time() . '.zip');

// Max Anzahl an Datensätzen pro Datei
define('JTLSEARCH_FILE_LIMIT', 5000);
define('JTLSEARCH_FILE_NAME', 'export_');
define('JTLSEARCH_FILE_NAME_SUFFIX', '.jtl');

define('JTLSEARCH_PRODUCT_EXCLUDE_ATTR', 'nosearch');
